### ISSUE TITLE
Not working if the property name has camel casing in it.

### ISSUE THREAD

**Issue by Debananda** [eee-c/angular-bind-polymer#18]
The directive is not working for polymer property name with came casing. probably need to rewrite the regex again  var _match = $attr[prop].match(/\{\{\s*([\.\w]+)\s*\}\}/);

**Comment by eee-c** [comment]
This _should_ work. The `\w` in the regex matches any non-whitespace character -- lower and uppercase.  In fact, I'm actively using this for camel case Polymer properties so I'm surprised this is causing trouble.

I'm not saying that there isn't a problem. There likely is and, even more likely, I'm misunderstanding your description :)

But... I'll need a test case that demonstrates the problem. Would it be possible to modify the Karma tests in this repos to demonstrate the bug and submit a pull request? The PR doesn't have to include a fix, but a failing test would be fantastic.

**Comment by Debananda** [comment]
I have updated the paramter **out** to **outValue**... I have attached the codes below have a look
x-double.html
-----------------
`<link rel="import" href="../bower_components/polymer/polymer.html">
<dom-module name="x-double"  attributes="in outValue">
  <template></template>
  <script>
    Polymer({
      is: "x-double",
      properties: {
        in: {
          type: Number,
          value: 0,
          observer: 'inChanged'
        },
        outValue: {
          type: Number,
          reflectToAttribute: true
        }
      },
      ready: function(){
        this.inChanged();
      },
      inChanged: function(){
        this.outValue = parseInt(this.in) * 2;
      }
    });
  </script>
</dom-module>`

index.html
----------------
`<p>
        in:<br>
        <input type=text value="6" ng-model="in">
        <pre ng-bind="in"></pre>
      </p>
      <p>
        out:
        <pre ng-bind="doubled"></pre>
      </p>
        <x-double bind-polymer in="{{in}}" out-value="{{doubled}}" disabled test="test"></x-double>
      </div>`

check this.. this is failing. here doubled is not  getting updated

**Comment by Debananda** [comment]
@eee-c : did you get a chance to look into the snippet i have provided.

**Comment by eee-c** [comment]
Much thanks for the snippet. I'm crazy swamped these days (who isn't
though?), but I want to get to this today or tomorrow.

I _really_ appreciate the snippet -- it's a huge help! I think I see the
problem and am reasonably sure I can fix it. I'll let you know shortly...

On Sat, Sep 10, 2016 at 1:15 AM, Debananda Mohanty <notifications@github.com
